### PR TITLE
Fix Compilation errors for privilege and Zifenci tests.

### LINKED ISSUE #343: Test that traps throws compilation error using latest GNU Toolchain
Privilege tests (and c.ebreak) throws error and cannot be compiled using the latest version of the toolchain. I'm using a pre-build nightly release (64-bit-elf-ubuntu) available [here](https://github.com/riscv-collab/riscv-gnu-toolchain/releases/tag/2023.04.29). 
### Reason
Whenever there is a trap, the trap-handler executes `fence.i` instruction [here](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/riscv-test-suite/env/arch_test.h#L903) (which is defined [here](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/riscv-test-suite/env/arch_test.h#L142)). The latest version of the toolchain expects `zifencei` defined as part of ISA string in `march` flag if we want to execute fence.i . And it is not defined in any of the tests under RVTEST_ISA (from where RISCOF picks up ISA string for march), even in Fencei.S test ([link](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/riscv-test-suite/rv32i_m/Zifencei/src/Fencei.S#L13)). Hence, toolchain throws the error on execution of fence instruction without using zifencei in `march` flag.

### PR DESCRIPTION
**Pull request by Abdulwadoodd**
### Related Issue

This PR fixes #343.

### Description
- The default definition of `RVMODEL_FENCEI` is set to `nop` instruction. This stops the compilation when running tests (using the latest GNU toolchain) on the implementation that does not support `Zifencei`. Implementation may change the definition of `RVMODEL_FENCEI` in the `model_test.h`. 
- The ISA string is updated for `Zifencei` tests (RV32 and RV64) which is required by `march` of the latest toolchain.

### CODE REVIEW

**Review by pawks — APPROVED** [review]

File: riscv-test-suite/env/arch_test.h [hunk 1]
```diff
@@ -138,8 +138,15 @@
...
+//==========================================================================================
+// By default, it is defined as nop for the implementation that does not support Zifencei
+// Implementations that support Zifencei may use the fence.i instruction.
+// This only gets executed if xTVEC is not writable to point to the trap trampoline, 
+// and if it isn't writable, the model better have the zifencei extension implemented.
+//==========================================================================================
+
 #ifndef   RVMODEL_FENCEI
-  #define RVMODEL_FENCEI fence.i                                // make sure ifetches get new code
+  #define RVMODEL_FENCEI nop
```
Comment (allenjbaum) [inline riscv-test-suite/env/arch_test.h:149]: The problem with this fix is that when an implementation supports Zifencei, and doesn't allow writing xTVEC, then tests may fail , because they execute a nop, and the test spec doesn't say anything about requiring DUTs to define  RVMODEL_FENCEI to be fence.i under this (or any other) circumstance.
What I think I'd like to see is (something like):
#ifndef   RVMODEL_FENCEI
  #ifndef ZIFENCE
       #define RVMODEL_FENCEI nop
    #else                            
       #define RVMODEL_FENCEI fence.i  
    #endif
#endif

Comment (pawks) [reply riscv-test-suite/env/arch_test.h:149]: I think its okay to have the default to be a `nop` as that is what the base spec supports. If the model implements non-coherent I&D streams and requires synchronization using fence.i, the model can define the RVMODEL_FENCEI macro as is. Using ZIFENCE under a `ifndef` in this case raises the question who defines that macro. Is it the implementation header file or riscof? I am comfortable with either of the solutions, but requires clear indication in the documentation.

Comment (allenjbaum) [reply riscv-test-suite/env/arch_test.h:149]: I agree that it is OK, in the sense that it is legal, but if they implement Zifencei, I don't want them to have to take the extra step of defining this (if they even notice that they need to and then have to go try to debug this, which won't be easy). Anything we can do to smooth the path is what we should be doing. The only reason that they should have to define this explicity is if they don't have coherent streams AND they don't implement Zifencei, in which case they can insert their own custom solution in place of that. Otherwise, they shouldn't even know about this. 
If it is custom, then it's the implementation header file; riscof will have no idea what their custom solution is.

Comment (Abdulwadoodd) [reply riscv-test-suite/env/arch_test.h:149]: Now there are two macros:
1. `RVMODEL_FENCEI`
2. `ZIFENCE`

> The only reason that they should have to define this explicity is if they don't have coherent streams AND they don't implement Zifencei

By "this" you mean `ZIFENCE` or `RVMODEL_FENCEI` or both? (which has to go into the documentation)
Can we do this, instead:
```
#ifndef RVMODEL_FENCEI
    #define RVMODEL_FENCEI nop
#else                            
    #define RVMODEL_FENCEI fence.i 
#endif
```
This does the same job as you are suggesting? (and it is working) but without using `ZIFENCE`

Comment (Abdulwadoodd) [reply riscv-test-suite/env/arch_test.h:149]: Please ignore my last comment.

> Otherwise, they shouldn't even know about this.

I understood why it is this way. Updating the commit.

Comment (Abdulwadoodd) [reply riscv-test-suite/env/arch_test.h]: Changes are upstreamed. Please review and merge

**Review by allenjbaum — APPROVED** [review]
This will do the trick
