### PR TITLE
Split FLEN into TEST_FLEN and CONFIG_FLEN to make ZicsrF work on DUTs with only F

### LINKED ISSUE #1223: Wrong FLEN when test march includes D but DUT only implements F
**Describe the bug**
Running `make CONFIG_FILES=config/cores/cve4/cv32e40p-v2-rv32mcf/test_config.yaml` hangs indefinitely on `work/cv32e40p-v2-rv32mcf/build/priv/ZicsrF/ZicsrF-00.sig` (Sail reference model run). Root cause: the build system compiles `ZicsrF-00.sig.elf` with `-DFLEN=64` (because the test's march includes `d`), causing `fsd` (double-precision store) to be emitted. But the DUT's `sail.json` has `D: supported: false`, so Sail traps on `fsd` as an
illegal instruction.

**To Reproduce**
make -j1 CONFIG_FILES=config/cores/cve4/cv32e40p-v2-rv32mcf/test_config.yaml  EXTENSIONS=ZicsrF EXCLUDE_EXTENSIONS= DEBUG=1 JOBS=1
hangs — kill after ~60s
tail work/cv32e40p-v2-rv32mcf/build/priv/ZicsrF/ZicsrF-00.sig.trace

Following changes have to be made to existing config for full run:
- add F_SUPPORTED to rvtest_config.h #1150 adds this
- mtimeaddress and mtimecmp_address added ( #934 workaround)
- move memory region from 0x0 in sail.json or ACCESS_FAULT_ADDRESS outside memory #1187 

**Text output/Error Messages**
```
[3234] [M]: 0x000043F8 fsub.s f7, f13, f13   # executes fine, sets mstatus.FS=Dirty
...
[3244] [M]: 0x00004420 illegal 0x72b027       # fsd — illegal with D=false
trapping from M to M to handle illegal-instruction
```
**Additional context**

### 1. ZicsrF test march includes D

`ZicsrF.py` declares:

```python
@add_priv_test_generator(
    "ZicsrF",
    required_extensions=["Zicsr", "F"],
    march_extensions=["Zicsr", "F", "D", "Zfh"],
)
```

The generator writes `MARCH: rv${XLEN}ifd_zicsr_zfh` into the test's config header. D is intentionally included so that `#ifdef D_SUPPORTED` optional coverpoints can be conditionally compiled in for DUTs that have the D extension.

### 2. FLEN computed from test march, not DUT extensions

`parse_test_constraints.py` — `TestMetadata.flen`:

```python
@property
def flen(self) -> str:
    base = self.march.split("_")[0].lower()
    if "q" in base: return "128"
    if "d" in base or "g" in base: return "64"   # ← "d" is in rv32ifd → FLEN=64
    if "f" in base: return "32"
    return "32"
```

`build_plan.py` — `gen_compile_tasks`:

```python
march = test_metadata.march.replace("${XLEN}", str(xlen))
flen = test_metadata.flen          # → "64"
...
sig_elf_cmd = [..., f"-DFLEN={flen}", ...]   # → -DFLEN=64
```

### 3. FLEN=64 causes fsd to be emitted for F-only code paths

`tests/env/utils.h`:

```c
#if FLEN==32
  #define FSREG fsw
#elif FLEN==64
  #define FSREG fsd     // ← selected because DFLEN=64
#endif
```

`tests/env/signature.h` — `RVTEST_SIGUPD_F` uses `FSREG` to save the FP result to the signature area. With FLEN=64, this emits `fsd` even though the result is a single-precision float (f7 from `fsub.s`).

Confirmed by objdump of `ZicsrF-00.sig.elf`:

```
000043f8 <ZicsrF_cg_cp_fflags_set_m_NV>:
    43f8:  08d6f3d3   fsub.s  f7,f13,f13    # single-precision — F only
    ...
    4420:  0072b027   fsd     f7,0(x5)      # double store — D required ← WRONG
```

The `rvtest_config.h` correctly omits `#define D_SUPPORTED`, so `#ifdef D_SUPPORTED` blocks in the test are compiled out. But FLEN=64 affects FSREG globally, including F-only signature update paths.

### PR DESCRIPTION
**Pull request by jordancarlin**
Fixes #1223.

### CODE REVIEW

**Comment by jordancarlin** [comment]
Confirmed this works for DUTs that only have F and still gets full coverage both for DUTs with only F and with both F and D. We need to get a config added to CI that only has F without D to avoid issues like this in the future.

File: tests/env/signature.h [hunk 1]
```diff
@@ -111,24 +111,32 @@
...
 // Floating point values are stored to memory and then loaded back into integer registers
 // for comparison, to avoid issues with NaN that arise from using feq. There is no way to
 // directly transfer a floating point value to an integer register without Zfa when FLEN > XLEN.
-#if FLEN == 128 && XLEN == 32
+#if CONFIG_FLEN == 128 && XLEN == 32
   #error "Q on RV32 is not supported yet."
 #endif
-#if FLEN > XLEN
+#if CONFIG_FLEN > XLEN
   #ifdef RVTEST_SELFCHECK
```
[the remark this answers is not in the document]
Comment (jordancarlin) [reply tests/env/signature.h:141]: Good catch Copilot! Working on a fix for this.

File: tests/env/failure_code.h [hunk 2]
```diff
@@ -242,10 +242,12 @@
         sw x6, 260(DEFAULT_TEMP_REG)      # record failing_reg
 
         # Load bad FP value from scratch memory (written by FSREG in the sigupd macro)
+        # Use FP_LREG so we read exactly the CONFIG_FLEN bits FSREG stored,
```
Comment (davidharrishmc) [inline tests/env/failure_code.h:245]: "// See tests/env/utils.h for an explanation of CONFIG_FLEN and TEST_FLEN"

File: tests/env/signature.h [hunk 3]
```diff
@@ -111,24 +111,32 @@
 // RVTEST_SIGUPD_F(sigptr, linkreg, tempreg, ftempreg, sigreg, instptr, strptr)
 // Checks both a floating point result register and fflags against the signature.
 // Compares the float value in sigreg with the value in memory at 0(sigptr),
-// then uses RVTEST_SIGUPD_FFLAGS to check fflags. When FLEN > XLEN, the float
-// value requires 2 signature entries (low and high words), plus 1 for fflags
-// (total 3*SIG_STRIDE). When FLEN == XLEN, uses 1 entry for the float value
-// plus 1 for fflags (total 2*SIG_STRIDE).
+// then uses RVTEST_SIGUPD_FFLAGS to check fflags. When CONFIG_FLEN > XLEN, the
```
Comment (davidharrishmc) [inline tests/env/signature.h:114]: "// See tests/env/utils.h for an explanation of CONFIG_FLEN and TEST_FLEN"

File: tests/env/utils.h [hunk 4]
```diff
@@ -43,34 +43,101 @@
     #define LREG lq
 #endif
 
-# FLEN specific macros
-#define FREGWIDTH (FLEN>>3)      // in units of #bytes
+// FLEN specific macros
+// ============================================================================
+// Two distinct FLEN values
+// ----------------------------------------------------------------------------
+// TEST_FLEN  — the FLEN this test file was *generated* for. Supplied by the
```
Comment (davidharrishmc) [inline tests/env/utils.h]: Start with explaining the problem that is being solved.

File: tests/env/utils.h [hunk 5]
```diff
@@ -43,34 +43,101 @@
...
+//               needs to be sliced into two integer loads (the
+//               "CONFIG_FLEN > XLEN" path in signature.h).
+//
+//               CONFIG_FLEN must not exceed TEST_FLEN because the assembler
+//               only knows instructions up to that width (e.g. an F-only test
+//               with march=rv64if cannot assemble fsd). It must not exceed
+//               the DUT's capability either (e.g. a priv test generated with
+//               D in its march but run on an F-only DUT must not emit fsd).
+//               See issue #1223.
+// ============================================================================
```
Comment (davidharrishmc) [inline tests/env/utils.h:88]: Give examples of TEST_FLEN and CONFIG_FLEN for RV32/64 D/F and show how they solve the problem described above.

File: tests/env/utils.h [hunk 6]
```diff
@@ -43,34 +43,101 @@
...
+#endif
+
+#define FREGWIDTH (TEST_FLEN>>3)     // data/signature slot width, in bytes
+
+// Derive the DUT's raw FP capability from its rvtest_config.h defines.
+#if defined(Q_SUPPORTED)
+  #define _DUT_FLEN 128
+#elif defined(D_SUPPORTED)
+  #define _DUT_FLEN 64
+#elif defined(F_SUPPORTED) || defined(ZFH_SUPPORTED) || defined(ZFHMIN_SUPPORTED) || defined(ZFBFMIN_SUPPORTED)
```
Comment (davidharrishmc) [inline tests/env/utils.h]: Don't all these other Zf* depend on F_SUPPORTED so you only need to check F_SUPPORTED and could leave it as #else with no check?

File: tests/env/utils.h (hunk 4 above)
Comment (davidharrishmc) [reply tests/env/utils.h]: "was generated for" is unclear because most readers won't fully understand the generation process.  Explain how to know what it was generated for.

File: tests/env/utils.h [hunk 7]
```diff
@@ -278,9 +346,9 @@
   .option pop
 #endif
 
-# Alignment size for LA macro. Must be larger than the longest instruction
-# sequence that the la pseudo-instruction can expand into (to account for the jump hack).
-# On some rv64 targets, this may need to be increased to 6.
+// Alignment size for LA macro. Must be larger than the longest instruction
+// sequence that the la pseudo-instruction can expand into (to account for the jump hack).
+// On some rv64 targets, this may need to be increased to 6.
```
Comment (davidharrishmc) [inline tests/env/utils.h:368]: How will we know which rv64 targets need 6 and when to change it?

Comment (jordancarlin) [reply tests/env/utils.h:368]: This comment has been here for a while. I think @allenjbaum is best suited to answer this.

**Review by davidharrishmc — APPROVED** [review]
